library(lubridate)
data<-read.table('household_power_consumption.txt',header=TRUE,sep=';',as.is = TRUE)
data<-transform(data,Date = as.character(Date))
data<-transform(data,Date = dmy(Date))
LG_vec1<-which(year(data$Date)==2007 & month(data$Date)==2 & day(data$Date)==1)
LG_vec2<-which(year(data$Date)==2007 & month(data$Date)==2 & day(data$Date)==2)
LG_vec<-c(LG_vec1,LG_vec2)
sub<-data[LG_vec,]
sub$Date<-as.character(sub$Date)
sub$Time<-as.character(sub$Time)
head(sub$Date)
head(sub$Time)
sub$newCol<-paste(sub$Date,sub$Time)
head(sub$newCol)
sub$newCol<-as.POSIXct(sub$newCol, format="%Y-%m-%d %H:%M:%S")


sub<-transform(sub,Global_active_power=as.numeric(Global_active_power))
sub<-transform(sub,Global_reactive_power=as.numeric(Global_reactive_power))
sub<-transform(sub,Voltage=as.numeric(Voltage))
sub<-transform(sub,Global_intensity=as.numeric(Global_intensity))
sub<-transform(sub,Sub_metering_1=as.numeric(Sub_metering_1))
sub<-transform(sub,Sub_metering_2=as.numeric(Sub_metering_2))
sub<-transform(sub,Sub_metering_3=as.numeric(Sub_metering_3))
png("plot3.png",width=480,height = 480,units = "px")
plot(Sub_metering_1~newCol,sub,type="l", xlab = '', ylab = 'Energy Sub Metering')
points(Sub_metering_2~newCol,sub,type="l",col='red')
points(Sub_metering_3~newCol,sub,type="l",col='blue')
legend('topright', legend=c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),
       col=c("black","red", "blue"), lty=c(1,1,1), cex=0.5)
dev.off()