library(lubridate)
data<-read.table('household_power_consumption.txt',header=TRUE,sep=';',as.is = TRUE)
data<-transform(data,Date = as.character(Date))
data<-transform(data,Date = dmy(Date))
LG_vec1<-which(year(data$Date)==2007 & month(data$Date)==2 & day(data$Date)==1)
LG_vec2<-which(year(data$Date)==2007 & month(data$Date)==2 & day(data$Date)==2)
LG_vec<-c(LG_vec1,LG_vec2)
sub<-data[LG_vec,]
sub<-transform(sub,Global_active_power=as.numeric(Global_active_power))
sub<-transform(sub,Global_reactive_power=as.numeric(Global_reactive_power))
sub<-transform(sub,Voltage=as.numeric(Voltage))
sub<-transform(sub,Global_intensity=as.numeric(Global_intensity))
sub<-transform(sub,Sub_metering_1=as.numeric(Sub_metering_1))
sub<-transform(sub,Sub_metering_2=as.numeric(Sub_metering_2))
sub<-transform(sub,Sub_metering_3=as.numeric(Sub_metering_3))
png("plot1.png",width=480,height = 480,units = "px")
hist(sub$Global_active_power,col = 'red', xlab = "Global Active Power (Kilowatts)",main="Global Active Power")
dev.off()